In [1]:
import os
import pandas as pd

In [2]:
match_txt = open("Stats-2011.txt")
line_lst = match_txt.readlines()

In [3]:
combined_txt = ''.join(line_lst)

In [4]:
combined_txt.split('\n\n')[0]

'Match: 7457\n48.5 Possession % 51.5\n3 Shots on target 3\n9 Shots 12\n631 Touches 659\n434 Passes 465\n23 Tackles 21\n21 Clearances 11\n4 Corners 5\n2 Offsides 5\n2 Yellow cards 2\n14 Fouls conceded 11'

In [5]:
attribute_lst = ['MatchID', 'Possession_home',
 'Possession_away',
 'Shots_on_target_home',
 'Shots_on_target_away',
 'Shots_home',
 'Shots_away',
 'Touches_home',
 'Touches_away',
 'Passes_home',
 'Passes_away',
 'Tackles_home',
 'Tackles_away',
 'Clearances_home',
 'Clearances_away',
 'Corners_home',
 'Corners_away',
 'Offsides_home',
 'Offsides_away',
 'Yellow_cards_home',
 'Yellow_cards_away',
 'Fouls_conceded_home',
 'Fouls_conceded_away',
 'Red_cards_home',
 'Red_cards_away']

match_csv = open('Stats-2011.csv', 'w')

attribute_name = ','.join(attribute_lst) + '\n'

match_csv.write(attribute_name)

for row in combined_txt.split('\n\n'):
    row = row.replace("% ", "")
    data = row.split('\n')
    
    try:
        data.remove('')
    except:
        pass
    
    data_dict = {key : '' for key in attribute_lst}
    
    for i in range(len(data)):
        
        data_line = data[i].split(' ')
        if(i == 0):
            match_id = data_line[1]
            data_dict['MatchID'] = match_id
        else:
            home_data = data_line[0]
            away_data = data_line[-1]
            
            attribute = '_'.join(data_line[1:-1]) 
            
            attribute_h = attribute + "_home"
            attribute_a = attribute + "_away"
            
            data_dict[attribute_h] = home_data
            data_dict[attribute_a] = away_data
        
    new_line = ','.join(data_dict.values()) + '\n'
    match_csv.write(new_line)

match_csv.close()

In [6]:
res_df = pd.read_csv('MatchResults-2011.csv')
stats_df = pd.read_csv('Stats-2011.csv')

In [7]:
res_df.head()

   MatchID    Home_team  Away_team  Score_home  Score_away
0     7457  Aston Villa  Liverpool           1           0
1     7458       Bolton   Man City           0           2
2     7459      Everton    Chelsea           1           0
3     7460       Fulham    Arsenal           2           2
4     7461      Man Utd  Blackpool           4           2

In [8]:
stats_df.head()

,MatchID,Possession_home,Possession_away,Shots_on_target_home,Shots_on_target_away,Shots_home,Shots_away,Touches_home,Touches_away,Passes_home,...,Corners_home,Corners_away,Offsides_home,Offsides_away,Yellow_cards_home,Yellow_cards_away,Fouls_conceded_home,Fouls_conceded_away,Red_cards_home,Red_cards_away
0,7457.0,48.5,51.5,3.0,3.0,9.0,12.0,631.0,659.0,434.0,...,4.0,5.0,2.0,5.0,2.0,2.0,14.0,11.0,NaN,NaN
1,7458.0,40.5,59.5,2.0,7.0,15.0,17.0,520.0,709.0,309.0,...,6.0,4.0,0.0,1.0,1.0,1.0,13.0,11.0,1.0,0.0
2,7459.0,36.1,63.9,2.0,5.0,12.0,19.0,465.0,714.0,278.0,...,6.0,5.0,2.0,5.0,2.0,2.0,12.0,16.0,1.0,0.0
3,7460.0,32.2,67.8,3.0,5.0,9.0,13.0,460.0,802.0,272.0,...,5.0,3.0,4.0,2.0,2.0,1.0,14.0,7.0,1.0,0.0
4,7461.0,58.5,41.5,7.0,4.0,20.0,15.0,745.0,585.0,561.0,...,8.0,8.0,3.0,1.0,2.0,1.0,9.0,6.0,NaN,NaN

In [9]:
merged_df = pd.merge(res_df, stats_df, on = "MatchID")
merged_df.fillna(0, inplace = True)

In [10]:
merged_df.to_csv('result-2011.csv', index = False)

In [15]:
masterdata = pd.read_csv('masterdata.csv')

In [16]:
masterdata.shape

(4556, 29)